# Generated by Django 3.1.1 on 2020-09-28 02:59

import apps.api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=apps.api.utils.get_random_string, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.CharField(default=apps.api.utils.get_random_string, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('data_type', models.CharField(choices=[('i', 'int'), ('f', 'float'), ('s', 'string')], max_length=7)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('gateway_id', models.CharField(max_length=30)),
                ('rssi', models.FloatField()),
                ('snr', models.FloatField()),
                ('raw_value', models.CharField(max_length=30)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
        ),
    ]
