# Generated by Django 3.0.7 on 2020-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201127_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mqtt_passwd',
            field=models.CharField(default='123456', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_user',
            field=models.CharField(default='123', max_length=6),
            preserve_default=False,
        ),
    ]
