# Generated by Django 3.1.1 on 2020-09-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200923_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
