# Generated by Django 3.1.1 on 2020-09-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200923_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
